### ISSUE TITLE
Doesn't support IN queries?

### ISSUE THREAD

**Issue by grncdr** [joeldrapper/literal_enums-rails#1]
It seems like I can't pass an array of enum singletons to `where`. I've prepared an example repo, the relevant line is [this one](https://github.com/grncdr/literal_enum-issue/blob/development/app/models/post.rb#L10)

The repo also contains a [single test case](https://github.com/grncdr/literal_enum-issue/blob/development/test/models/post_test.rb#L5) that demonstrates what happens if you try to query that scope.

**Comment by joeldrapper** [comment]
It looks like ActiveRecord is serialising the value twice, so this method is hit once with an Enum and once again with a string.

https://github.com/joeldrapper/literal_enums-rails/blob/2a663e3b82aca96c65171116a82fdfa5813012ad/lib/literal_enums/rails/enum_type.rb#L17-L19

It should be enough to add a guard to return the value itself unless the value is an instance of the enum.

**Comment by grncdr** [comment]
Yep, I just checked it with a [monkey patch](https://github.com/grncdr/literal_enum-issue/commit/544d403c9ae37f94103f27036c1fb53a5b84fa3b) in the test repo and the test case passes, so I've opened a PR here.
